### ISSUE TITLE
Deadfile for libraries should respect exports

### ISSUE THREAD

**Issue by heneryville** [M-Izadmehr/deadfile#1]
Super project! Thank you.

I've got a use case where my project is a library that exports much of it's functionality for 3rd parties to use. I want to know what files are not getting exported. It seems like this could have an option to run in library mode that tells you not just what isn't imported, but also what isn't exported.

**Comment by M-Izadmehr** [comment]
Hum, let me see if I get your point clearly.
If the use case is for a library, and you start with the `main` file, and set the search `--dir` inside the library, basically any file which is not used in the project is still dead code.
But what you are looking for is different, it is to add the possibility to show all the files which are not exported in `main`. it means that almost all the files in the project (which are not directly exported in main) are going to be considered as such.
If I got your purpose correctly, I guess it does not make sense to add such a particular use case, but I think another option might be more interesting, which is the ability to write custom search function to define what you are looking for. How does it sound?

**Comment by heneryville** [comment]
As I'm reading through this code more, I think that what you've got right now actually works fine for the library use case. The code that handles "ImportFromExport" will correctly identify exported code as an import, and consider those files as used, so this project does work for libraries.

It turned out that this wasn't working for me due to a bug associated with running Deadfile on a windows machine. I've submitted a PR to fix that.

**Comment by M-Izadmehr** [comment]
Cool thanks man.
